FROM python:3.10-alpine
WORKDIR /app
COPY ./app /app
COPY requirements.txt .
RUN apk add --no-cache gcc musl-dev libffi-dev && \
    pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
CMD ["python", "main.py"]
